/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hang
 */
public class BaiTapForm72 extends javax.swing.JFrame {
    
   public Float TinhTien(float TongSoDien){
            float iTongSoDien = TongSoDien;
            float iThanhTien = 0f;
            if(iTongSoDien > 300){
                iThanhTien +=(iTongSoDien - 300) *4000;
                iTongSoDien = 300;
            }
            if(iTongSoDien > 200){
                iThanhTien += (iTongSoDien - 200) * 2500;
                iTongSoDien = 200;
            }
            if(iTongSoDien > 100){
                iThanhTien += (iTongSoDien - 100) * 2000;
                iTongSoDien = 100;
            }
            if(iTongSoDien > 50){
                iThanhTien += (iTongSoDien - 50) *1000;
                iTongSoDien = 50;
            }
            
            iThanhTien += iTongSoDien * 500;
            
            return iThanhTien;
        } 
    public BaiTapForm72() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnTinh = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCSC = new javax.swing.JTextField();
        txtCSM = new javax.swing.JTextField();
        txtTongSoDien = new javax.swing.JTextField();
        txtThanhTien = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tính tiền điện");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Tính tiền điện theo chỉ số đồng hồ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 29));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Chỉ số cũ: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Chỉ số mới: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Tổng số điện: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Thành tiền:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 20));

        btnTinh.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnTinh.setText("Tính");
        btnTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhActionPerformed(evt);
            }
        });
        getContentPane().add(btnTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 110, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("VNĐ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        txtCSC.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txtCSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 110, -1));

        txtCSM.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txtCSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 110, -1));

        txtTongSoDien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTongSoDien.setEnabled(false);
        getContentPane().add(txtTongSoDien, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 110, -1));

        txtThanhTien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtThanhTien.setEnabled(false);
        txtThanhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThanhTienActionPerformed(evt);
            }
        });
        getContentPane().add(txtThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtThanhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThanhTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThanhTienActionPerformed

    private void btnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhActionPerformed
        // TODO add your handling code here:
        float csc = Float.parseFloat(txtCSC.getText());
        float csm = Float.parseFloat(txtCSM.getText());
        float tong = csm - csc;
        txtTongSoDien.setText(String.valueOf(tong));
        txtThanhTien.setText(String.valueOf(TinhTien(tong)));
    }//GEN-LAST:event_btnTinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaiTapForm72.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaiTapForm72.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaiTapForm72.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaiTapForm72.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaiTapForm72().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCSC;
    private javax.swing.JTextField txtCSM;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTongSoDien;
    // End of variables declaration//GEN-END:variables
}
