/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hang
 */
public class BaiTapForm73 extends javax.swing.JFrame {
    
    public Long TinhGiaiThua(int x){
        Long kq =1l;
        if(x<0){
            return -1l;
        }
        for(int i = 1;i<=x;i++)
        {
            kq = kq*i;
        }
        return kq;
    }
    /**
     * Creates new form BaiTapForm73
     */
    public BaiTapForm73() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGiaTriX = new javax.swing.JTextField();
        txtKetQua = new javax.swing.JTextField();
        btnTinh = new javax.swing.JButton();
        btnNhaplai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tính giai thừa");
        setAutoRequestFocus(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tính giai thừa của x");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nhập x:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Kết quả:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        txtGiaTriX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTriXActionPerformed(evt);
            }
        });
        getContentPane().add(txtGiaTriX, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 140, 30));

        txtKetQua.setEnabled(false);
        getContentPane().add(txtKetQua, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 140, -1));

        btnTinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTinh.setText("Tính ");
        btnTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhActionPerformed(evt);
            }
        });
        getContentPane().add(btnTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 90, -1));

        btnNhaplai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNhaplai.setText("Nhập lại");
        btnNhaplai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaplaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnNhaplai, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGiaTriXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTriXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTriXActionPerformed

    private void btnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(txtGiaTriX.getText());
        int KQ = 1 ;
        txtKetQua.setText(String.valueOf(TinhGiaiThua(x)));
        
    }//GEN-LAST:event_btnTinhActionPerformed

    private void btnNhaplaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaplaiActionPerformed
        // TODO add your handling code here:
        txtGiaTriX.setText("");
        txtKetQua.setText("");
    }//GEN-LAST:event_btnNhaplaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaiTapForm73.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaiTapForm73.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaiTapForm73.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaiTapForm73.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaiTapForm73().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhaplai;
    private javax.swing.JButton btnTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtGiaTriX;
    private javax.swing.JTextField txtKetQua;
    // End of variables declaration//GEN-END:variables
}
