/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JFrame;

/**
 *
 * @author Hang
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_KHCount = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_SVCount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_sv = new javax.swing.JMenu();
        jmenu_addsv = new javax.swing.JMenuItem();
        menuQuanLi = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuThemKH = new javax.swing.JMenuItem();
        MenuQuanLyKH = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuThemDiem = new javax.swing.JMenuItem();
        menuXoaSuaDiem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang Chủ");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jlabel_Username.setFont(new java.awt.Font("Britannic Bold", 2, 48)); // NOI18N
        jlabel_Username.setForeground(new java.awt.Color(153, 0, 153));
        jlabel_Username.setText("Welcome<#####>");

        jPanel2.setBackground(new java.awt.Color(255, 153, 204));

        lbl_KHCount.setBackground(new java.awt.Color(255, 102, 102));
        lbl_KHCount.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        lbl_KHCount.setForeground(new java.awt.Color(255, 255, 255));
        lbl_KHCount.setText("Số Lượng Khóa Học Hiện Hành =");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbl_KHCount, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lbl_KHCount)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        lbl_SVCount.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        lbl_SVCount.setForeground(new java.awt.Color(255, 255, 255));
        lbl_SVCount.setText("Số lượng Sinh viên =");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_SVCount, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(lbl_SVCount)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/house.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jlabel_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jlabel_Username)
                        .addGap(248, 248, 248)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 204));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(10, 10));
        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(121, 45));
        jMenuBar1.setRequestFocusEnabled(false);

        menu_sv.setBackground(new java.awt.Color(204, 204, 255));
        menu_sv.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_sv.setForeground(new java.awt.Color(204, 0, 204));
        menu_sv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Student Male_48px.png"))); // NOI18N
        menu_sv.setText("Sinh Viên");
        menu_sv.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        menu_sv.setIconTextGap(8);

        jmenu_addsv.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jmenu_addsv.setForeground(new java.awt.Color(51, 153, 255));
        jmenu_addsv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users (2).png"))); // NOI18N
        jmenu_addsv.setText("Thêm Sinh Viên");
        jmenu_addsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_addsvActionPerformed(evt);
            }
        });
        menu_sv.add(jmenu_addsv);

        menuQuanLi.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        menuQuanLi.setForeground(new java.awt.Color(0, 153, 255));
        menuQuanLi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/group.png"))); // NOI18N
        menuQuanLi.setText("Quản Lý Sinh Viên");
        menuQuanLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLiActionPerformed(evt);
            }
        });
        menu_sv.add(menuQuanLi);

        jMenuBar1.add(menu_sv);

        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setForeground(new java.awt.Color(204, 0, 204));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Training_48px.png"))); // NOI18N
        jMenu1.setText("Khóa Học");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        menuThemKH.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        menuThemKH.setForeground(new java.awt.Color(0, 153, 255));
        menuThemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/file.png"))); // NOI18N
        menuThemKH.setText("Thêm Khóa Học");
        menuThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThemKHActionPerformed(evt);
            }
        });
        jMenu1.add(menuThemKH);

        MenuQuanLyKH.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MenuQuanLyKH.setForeground(new java.awt.Color(0, 153, 255));
        MenuQuanLyKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/file_1.png"))); // NOI18N
        MenuQuanLyKH.setText("Quản Lý Khóa Học");
        MenuQuanLyKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuQuanLyKHActionPerformed(evt);
            }
        });
        jMenu1.add(MenuQuanLyKH);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(204, 0, 204));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/score.png"))); // NOI18N
        jMenu2.setText("Điểm");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        menuThemDiem.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        menuThemDiem.setForeground(new java.awt.Color(0, 204, 255));
        menuThemDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/a- (1).png"))); // NOI18N
        menuThemDiem.setText("Thêm Điểm");
        menuThemDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThemDiemActionPerformed(evt);
            }
        });
        jMenu2.add(menuThemDiem);

        menuXoaSuaDiem.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        menuXoaSuaDiem.setForeground(new java.awt.Color(0, 204, 204));
        menuXoaSuaDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh (1).png"))); // NOI18N
        menuXoaSuaDiem.setText("Sửa/Xóa Điểm");
        menuXoaSuaDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuXoaSuaDiemActionPerformed(evt);
            }
        });
        jMenu2.add(menuXoaSuaDiem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenu_addsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_addsvActionPerformed
        //Thêm thông tin sv
       SinhVien_GUI sv = new SinhVien_GUI();
         sv.setVisible(true);
         sv.pack();
         sv.setLocationRelativeTo(null);
         //Chỉ tắt form thông tin sv
         sv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jmenu_addsvActionPerformed

    private void menuQuanLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLiActionPerformed
        // TODO add your handling code here:
         QuanLySinhVien_GUI qlsv = new QuanLySinhVien_GUI();
         qlsv.setVisible(true);
         qlsv.pack();
         qlsv.setLocationRelativeTo(null);
         //Chỉ tắt form quản lí
         qlsv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuQuanLiActionPerformed

    private void menuThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThemKHActionPerformed
        // TODO add your handling code here:
         KhoaHoc_GUI kh = new KhoaHoc_GUI();
         kh.setVisible(true);
         kh.pack();
         kh.setLocationRelativeTo(null);
         //Chỉ tắt form thông tin sv
         kh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuThemKHActionPerformed

    private void MenuQuanLyKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuQuanLyKHActionPerformed
        // TODO add your handling code here:
         QuanLyKhoaHoc qlkh = new QuanLyKhoaHoc();
         qlkh.setVisible(true);
         qlkh.pack();
         qlkh.setLocationRelativeTo(null);
         //Chỉ tắt form quản lí
         qlkh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_MenuQuanLyKHActionPerformed

    private void menuXoaSuaDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuXoaSuaDiemActionPerformed
            // TODO add your handling code here:
             Diem_Update_GUI  updatediem = new Diem_Update_GUI();
             updatediem.setVisible(true);
             updatediem.setLocationRelativeTo(null);
               updatediem.pack();
             //Chỉ tắt form thông tin sv
             updatediem.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuXoaSuaDiemActionPerformed

    private void menuThemDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThemDiemActionPerformed
        // TODO add your handling code here:
        Diem_GUI  td = new Diem_GUI();
         td.setVisible(true);
         td.setLocationRelativeTo(null);
           td.pack();
         //Chỉ tắt form thông tin sv
         td.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuThemDiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuQuanLyKH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static final javax.swing.JLabel jlabel_Username = new javax.swing.JLabel();
    private javax.swing.JMenuItem jmenu_addsv;
    public static javax.swing.JLabel lbl_KHCount;
    public static javax.swing.JLabel lbl_SVCount;
    private javax.swing.JMenuItem menuQuanLi;
    private javax.swing.JMenuItem menuThemDiem;
    private javax.swing.JMenuItem menuThemKH;
    private javax.swing.JMenuItem menuXoaSuaDiem;
    private javax.swing.JMenu menu_sv;
    // End of variables declaration//GEN-END:variables
}
