/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baith2_sw;

import java.util.ArrayList;

/**
 *
 * @author Hang
 */
public class StudentGUI extends javax.swing.JFrame {
    ArrayList<StudentInfo> dsSV ;
    /**
     * Creates new form StudentGUI
     */
    public StudentGUI() {
        initComponents();
        dsSV = new ArrayList<StudentInfo>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grGioiTinh = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        txtTen = new javax.swing.JTextField();
        txtNamSinh = new javax.swing.JTextField();
        raNam = new javax.swing.JRadioButton();
        raNu = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnNapVao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Họ tên: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Năm sinh");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 64, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Giới tính: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 110, -1, -1));

        btnThem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 162, -1, -1));
        jPanel1.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 170, -1));
        jPanel1.add(txtNamSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 170, -1));

        grGioiTinh.add(raNam);
        raNam.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        raNam.setText("Nam");
        jPanel1.add(raNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        raNu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        raNu.setText("Nữ");
        raNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raNuActionPerformed(evt);
            }
        });
        jPanel1.add(raNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 300, 200));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 470, 140));

        btnNapVao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNapVao.setText("Nạp vào");
        btnNapVao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNapVaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNapVao, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void raNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raNuActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        //tạo 1 đối tượng sinh viên tên là sv
        StudentInfo sv = new StudentInfo();
        //Gán các dữ liệu cho đối tượng sv
        sv.setTen(txtTen.getText());
        sv.setNs(txtNamSinh.getText());
        if(raNam.isSelected())
            sv.setGt("Nam");
        else
            sv.setGt("Nữ");
        dsSV.add(sv);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnNapVaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNapVaoActionPerformed
        // TODO add your handling code here:
        //set về rỗng
        txtArea.setText("STT \t Họ Tên \t Năm Sinh \t Giới Tính\n");
        int i = 0;
        //khai báo một đối tượng StudentInfo
        for(StudentInfo sv: dsSV)
        {
            txtArea.setText(txtArea.getText() + String.valueOf(i+1) + "\t " + sv.getTen() + "\t " + sv.getNs() + "\t "  + sv.getGt() + "\n" );
            
        }
        
    }//GEN-LAST:event_btnNapVaoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNapVao;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup grGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton raNam;
    private javax.swing.JRadioButton raNu;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtNamSinh;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
